name: BOFScale Build
on:
  push:
    branches: [ main ]
    paths:
      - 'tailscale/**'
      - '!**/*.md'
      - '!**/*.py'
      - '!**/*.cna'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ccob/windows-llvm-cross-msvc:latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Mark workspace as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build x64
        working-directory: tailscale
        run: >
          mkdir build-x86_64 &&
          cd build-x86_64 &&
          cmake -DCMAKE_BUILD_TYPE=MinSizeRel
          -DCMAKE_TOOLCHAIN_FILE=/opt/toolchain/x86_64-pc-windows-msvc.cmake .. &&
          cmake --build . -j4 &&
          cmake --install .

      - name: Build x86
        working-directory: tailscale
        run: >
          mkdir build-x86 &&
          cd build-x86 &&
          cmake -DCMAKE_BUILD_TYPE=MinSizeRel
          -DCMAKE_TOOLCHAIN_FILE=/opt/toolchain/i386-pc-windows-msvc.cmake .. &&
          cmake --build . -j4 &&
          cmake --install .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bofscale-dist
          path: tailscale/dist/
